# This file was generated by GoReleaser. DO NOT EDIT.
cask "kyp" do
  name "kyp"
  desc "Local-first terminal password manager with TOTP support"
  homepage "https://github.com/stickpro/kyp"
  version "0.2.1-RC"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kyp"

  on_macos do
    on_intel do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_darwin_amd64.tar.gz"
      sha256 "ca8f0953f893a73bff4364c1398850103263874f67179f0fd81f31c9dd80a7f3"
    end
    on_arm do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_darwin_arm64.tar.gz"
      sha256 "779271c8c7191a564b450a05ff3be3c1f566265f015b1ee3631191a085803735"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_linux_amd64.tar.gz"
      sha256 "456ec4807a7f72d2a6a66719d6eb27dede43a365b0c247bfecfa3cfc164848c1"
    end
    on_arm do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_linux_arm64.tar.gz"
      sha256 "c20302cc36742242a3ad2c058326fe81d0570a3bf536f86a2868b8ebfd3e737f"
    end
  end

  # No zap stanza required
end
