# This file was generated by GoReleaser. DO NOT EDIT.
cask "kyp" do
  name "kyp"
  desc "Local-first terminal password manager with TOTP support"
  homepage "https://github.com/stickpro/kyp"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kyp"

  on_macos do
    on_intel do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_darwin_amd64.tar.gz"
      sha256 "0059d4943433e1a7d0ec34e298b92f3bacc17f8c67ac09e978840ff05e13b74f"
    end
    on_arm do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_darwin_arm64.tar.gz"
      sha256 "55c75b5b702bc4fc83896cd8e1426cee3825961174607c21bf860e43f20a82fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_linux_amd64.tar.gz"
      sha256 "fca479e428d0eb5a61b10f2aaa36afe3bf549b397a6660b505ff61d28c8559d0"
    end
    on_arm do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_linux_arm64.tar.gz"
      sha256 "050d677ecd68c29eb967a059116256f4b00eff84a8aab52ab174cf37607bc4b3"
    end
  end

  # No zap stanza required
end
