# This file was generated by GoReleaser. DO NOT EDIT.
cask "kyp" do
  name "kyp"
  desc "Local-first terminal password manager with TOTP support"
  homepage "https://github.com/stickpro/kyp"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kyp"

  on_macos do
    on_intel do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_darwin_amd64.tar.gz"
      sha256 "3d928e45e22d03c5f3119c1ac8e59ae787ec53c5459af4740029ddfba26893f4"
    end
    on_arm do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_darwin_arm64.tar.gz"
      sha256 "fa18bcaabb4e8132181905b2ef8cc2ed2349e276ce7781d19894f2872a1e1290"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_linux_amd64.tar.gz"
      sha256 "6cb864d08ee161ffe46df173884fbfe30db828eddf229247417e15026a153131"
    end
    on_arm do
      url "https://github.com/stickpro/kyp/releases/download/v#{version}/kyp_#{version}_linux_arm64.tar.gz"
      sha256 "43b937708798e461bb6a40566a549658c88ae5cb9fd08f2d6608ac7e5ed9d7b2"
    end
  end

  # No zap stanza required
end
